### ISSUE TITLE
How do I get the SMPL model 'lbs_tj10smooth6_0fixed_normalized' ?

### ISSUE THREAD

**Issue by jbjeong** [bharat-b7/IPNet#1]
Hello, thank you for the great work.

I would like to test your code on the RenderPeople(free-model) mesh model,
but I got some problems.

The first is the the hard-coded file path.
[lib/smpl_paths.py code](https://github.com/bharat-b7/IPNet/blob/b5f8b3f2c447b21854b761ca6b397b1ea2e66864/lib/smpl_paths.py#L17)
`ROOT = '/BS/RVH/work/data/'`

And,
where could I find the SMPL model 'lbs_tj10smooth6_0fixed_normalized'
[lib/spml_paths.py code](https://github.com/bharat-b7/IPNet/blob/b5f8b3f2c447b21854b761ca6b397b1ea2e66864/lib/smpl_paths.py#L39)
`smpl_file = join(ROOT,
                             'smpl_models',
                             'lrotmin',
                             'lbs_tj10smooth6_0fixed_normalized',
                             self.gender,
                             'model.pkl')`

Thank you.

**Comment by bharat-b7** [comment]
Hi, You'd have to download SMPL from https://smpl.is.tue.mpg.de/ and change the ROOT according to where you place the smpl.

**Comment by jbjeong** [comment]
Thank you.
The model that is downloaded from Smpl homepage has the different filename.
And If I loaded that model, some attribute did not exist.
Do you think that it’s not important?

**Comment by bharat-b7** [comment]
I think the standard SMPL model should be fine. Share error msg if encountered.

**Comment by jbjeong** [comment]
I used the SMPL model: 'basicModel_f_lbs_10_207_0_v1.0.0.pkl'

The error message is below:
AttributeError: 'add' object has no attribute 'pose_subjects'

![스크린샷, 2020-08-31 15-20-52](https://user-images.githubusercontent.com/30853761/91688730-a642a600-eb9d-11ea-82b3-f677d66e4235.png)

**Comment by bharat-b7** [comment]
I've updated the code to not require pose_subjects. It now loads pre-computed prior.

**Comment by jbjeong** [comment]
Thank you!

**Comment by troylujc** [comment]
Hi, thank you for your great work
When I try smpl_registration/fit_SMPLD.py <scan_path.obj> <save_path>, I got FileNotFoundError:
No such file. '(SMPLpath)/templete/faces.npy'

Is this faces.npy file from SMPL model?

**Comment by bharat-b7** [comment]
faces.npy just contains smpl.f
