### ISSUE TITLE
kaolin install error

### ISSUE THREAD

**Issue by wangxihao** [bharat-b7/IPNet#14]
![image](https://user-images.githubusercontent.com/26833394/102764567-4bd08e00-43b6-11eb-9a5b-c777a765755a.png)

error:
/usr/local/cuda/include/cuda_fp16.hpp(1680): error: more than one instance of overloaded function "isinf" matches the argument list:
            function "isinf(float)"
            function "std::isinf(float)"
            argument types are: (float)

/usr/local/cuda/include/cuda_fp16.hpp(1691): error: more than one instance of overloaded function "isinf" matches the argument list:
            function "isinf(float)"
            function "std::isinf(float)"
            argument types are: (float)

/home/notebook/code/personal/80299257/conda/envs/ipnet/lib/python3.7/site-packages/torch/include/c10/core/TensorTypeSet.h(44): warning: integer conversion resulted in a change of sign

2 errors detected in the compilation of "/tmp/tmpxft_00005287_00000000-6_mesh_intersection_cuda_kernel.cpp1.ii".
error: command '/usr/local/cuda/bin/nvcc' failed with exit status 1

I was unable to install kaolin correctly, could anyone give me some advice,thank you !

configuration:
linux server
pytorch=1.4
cuda=10.0.130
Python=3.7.6

**Comment by ashwath98** [comment]
Can you run nvcc from your system?

**Comment by wangxihao** [comment]
@ashwath98  yes,nvcc works normal .
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:01_CDT_2018
Cuda compilation tools, release 10.0, V10.0.130

**Comment by wangxihao** [comment]
@ashwath98 have you installed Kaolin successfully?

**Comment by ashwath98** [comment]
I setup the repo on colab.
These were the steps I followed to install kaolin
git clone https://github.com/NVIDIAGameWorks/kaolin.git
cd kaolin
git checkout v0.1 (new API does not work with this repo)
python setup.py develop

**Comment by wangxihao** [comment]
Great! And have you run IP-Net with version0.1  kaolin successfully? I don't know which version of Kaolin can work .     Thank you!

**Comment by ashwath98** [comment]
Yeah

**Comment by wangxihao** [comment]
so bad ... still the same error, thank you anyway.

**Comment by wangxihao** [comment]
@ashwath98  Can you tell me the installing configuration?Such as python pytorch version?

**Comment by ljq2020** [comment]
I can tell you how to install kaolin

**Comment by wangxihao** [comment]
@ljq2020  Thank you and if you have any  idea with the error above?

**Comment by ljq2020** [comment]
check your email

**Comment by wangxihao** [comment]
Finally I installed v0.1 kaolin successfully with the help of my friend and the configuration is the same as before but the only one is the version of kaolin.
