### ISSUE TITLE
Fitting SMPL pose failed

### ISSUE THREAD

**Issue by Luciano07** [bharat-b7/IPNet#17]
Hi,
I'm using IPNet code by testing with this  scan file:
[scan_man.zip](https://github.com/bharat-b7/IPNet/files/5905515/scan_man.zip)
but code fails in pose optimization step. I used Ubuntu 18.04, and installed dependencies as readme file says. 
There are some screenshots of the results. 
the scan that i'm using:
![Screenshot from 2021-01-13 12-37-42](https://user-images.githubusercontent.com/26660371/106494017-a589a500-6498-11eb-9103-f764d79ae9e4.png)
and the inner surface(runinng 'test_IPNet.py'):
![Screenshot from 2021-02-01 13-41-23](https://user-images.githubusercontent.com/26660371/106489155-39587280-6493-11eb-84ed-f30badf559c2.png)
but for the SMPL optimization step(running 'fit_SMPL_IPNet.py'), pose optimization isn't working. I have shown a few iterations and the pose changes in the wrong direction with each iteration.
Iter 1: 
![Screenshot from 2021-02-01 13-46-19](https://user-images.githubusercontent.com/26660371/106489829-f2b74800-6493-11eb-8c47-2e1af8077775.png)
Iter 5: 
![Screenshot from 2021-02-01 13-47-07](https://user-images.githubusercontent.com/26660371/106489879-ffd43700-6493-11eb-8b6e-ce717784ba02.png)
Iter 15:
![Screenshot from 2021-02-01 13-47-38](https://user-images.githubusercontent.com/26660371/106489948-137f9d80-6494-11eb-9335-24db95455d40.png)
Iter 30:
![Screenshot from 2021-02-01 13-48-17](https://user-images.githubusercontent.com/26660371/106490064-301bd580-6494-11eb-8002-179946bd7420.png)

I tried to figure out whats the problem here, changing learning rate of Adam optimizer, but the result are the same.
I think the problem is in pose initialization, and the pose is taken from 'pose_prior.pkl'  obtaining mean smpl pose to initialize, but i don't understand how to change initial pose.
Other way is use a different optimizer than ADAM, any suggestions?

Any idea on how to fix it would be helpful.

**Comment by bharat-b7** [comment]
Hi, Can you check if the predicted part labels are correct?

**Comment by Luciano07** [comment]
Thanks for your quick response and great work,
The part labels are OK. 
The problem is in normalization of the input scan. In SMPL optimization, loss are calculated between non-normalized predicted inner surface and normalized SMPL model, obtaining enormous s2m and m2s loss.
I solved it normalizing the input scan using 'preprocess_scan.py' and setting 'SCALE=1.8' (default 1.5).  
Here my results: Inner surface, SMPL with pose optimized, and SMPL with pose ans shape optimized.
![Screenshot from 2021-02-11 18-09-16](https://user-images.githubusercontent.com/26660371/107699088-53186780-6c94-11eb-82c4-7c682f1c42fe.png)
I have another question, How can i set SCALE parameter in the right value?. I tried to use 1.5 as default value, and optimization fails.

Thanks again!

**Comment by bharat-b7** [comment]
SCALE corresponds to the rough the height of the person and correct scale helps in fast convergence of the fitting process. In case you want to automatically take care of this, you can reduce the learning rate and try to optimize the first beta parameter which roughly controls the height. The function 'optimize_pose_only' does this but you'll have to tweak the parameters to get optimal setting for your data.

**Comment by Luciano07** [comment]
Thanks for the explanation! Very clear for me.

**Comment by ljq2020** [comment]
Hi,
I meet the same problem, I have set 'SCALE=1.8', but it does not work. Do I need to change other codes?

**Comment by Luciano07** [comment]
Hi,
What input scan are you using?
I normalized the input scan before putting it in 'Test_IPNet.py', using this (simplification of 'preprocess_scan.py'):
[preprocess_only_scan.txt](https://github.com/bharat-b7/IPNet/files/6069590/preprocess_only_scan.txt)
After that I ran the demo using the '<your_obj>_scaled.obj' file.

**Comment by ljq2020** [comment]
Thanks for your quick response,
I didn't normalized the input scan before. Now I normalized it, using preprocess_only_scan.txt you gave. 
Here my results: SMPL with pose ans shape optimized and the final result. I think they are not very accurate. Do you have some suggestions to improve the accurate? 

![Uploading Screenshot from 2021-03-03 22-21-07.png…]()
![Uploading Screenshot from 2021-03-03 22-28-32.png…]()

**Comment by ljq2020** [comment]
Thanks for your quick response,
I didn't normalized the input scan before. Now I normalized it, using preprocess_only_scan.txt you gave. 
Here my results: SMPL with pose ans shape optimized and the final result. I think they are not very accurate. Do you have some suggestions to improve the accurate? 
![Screenshot from 2021-03-03 22-21-07](https://user-images.githubusercontent.com/63891270/109820802-4de58180-7c70-11eb-977f-59e8009a0e4f.png)
![Screenshot from 2021-03-03 22-28-32](https://user-images.githubusercontent.com/63891270/109820825-5473f900-7c70-11eb-9217-4f95d7c0e884.png)

**Comment by Luciano07** [comment]
I got the same results. I got confused and put the results of another scan in the comment above.
I don't know how to improve it.

**Comment by justanhduc** [comment]
Hi @bharat-b7 and @Luciano07,
I performed the same preprocessing as you did and got the following result. Did you have this problem before? Thanks.

![image](https://user-images.githubusercontent.com/15206627/111995525-61438880-8b5c-11eb-8d22-e062e88b537b.png)
