### ISSUE TITLE
Point to Surface Distance

### ISSUE THREAD

**Issue by ryancll** [bharat-b7/IPNet#18]

**Comment by ryancll** [comment]
Hi, thank you for the great work!

In this work, you fit the SMPLD by optimizing the point to surface distance instead of point cloud to point cloud chamfer loss. Will this design make the performance much better? 

Thank you!

**Comment by bharat-b7** [comment]
This really depends on the resolution of the two shapes. If you have dense (lots of points) shape, chamfer loss is good enough otherwise surface distance is better.

**Comment by ryancll** [comment]
Thank you!
