### ISSUE TITLE
Preprocess data for training

### ISSUE THREAD

**Issue by ljq2020** [bharat-b7/IPNet#21]
Hi,
I'm using `smpl_registration/fit_SMPLD.py` by testing with a scan file from Renderpeople, but I met a error `AttributeError: 'add' object has no attribute 'pose_subjects'`. How can I get this .pkl (such as `lbs_tj10smooth6_0fixed_normalized/male/model.pkl`) or a pre-computed prior (such as `assets/pose_prior.pkl`)
Any idea on how to fix it would be helpful.

**Comment by bharat-b7** [comment]
Hi, you can build your own prior using datasets such as AMASS or use the pre-computed prior `assets/pose_prior.pkl` by setting the `precomputed=True` to the `get_prior` function.
