### ISSUE TITLE
Suggestions to improve the execution time

### ISSUE THREAD

**Issue by Luciano07** [bharat-b7/IPNet#25]
Hi, 

First, thank for share you great job.
I'm running IPNet with my local computer, and the execution takes ~15 minutes on the inner-outer surface inference and ~7 minutes on  SMPL optimization.
Is there a way to improve the execution time of the method, that you recommend?
Maybe changing some parameter o doing some modification in code?

Any suggestion will be helpful for me.

Thanks in advance!

**Comment by bharat-b7** [comment]
Hi,
One of the most time consuming part in a forward pass is predicting occupancies for 256^3 grid points. If your gpu supports it you can increase the batch size of the query points using the `-batch_points` flag.
