### ISSUE TITLE
Could I get skeleton and skinning weights after alignments?

### ISSUE THREAD

**Issue by daisyranc** [bharat-b7/IPNet#26]
Hi,

First, thanks for this great work! I read your paper and knew that you could get skeleton and skinning weights after alignments. However, the results I got from your demo do not contain this information. How could I save skeleton and skinning weights accompany with *.obj results?

Thanks for your time and look forward to your reply!

**Comment by bharat-b7** [comment]
After running `test_IPNet.py` you would obtain the 3D meshes and SMPL correspondences. You can use these to fit SMPL model using `smpl_registration/fit_SMPL_IPNet.py`. Then take the SMPL skeleton and skinning weights.

**Comment by Daixinxin-cc** [comment]
@bharat-b7 Thanks for your nice reply! Now I can get the results smoothly! It is really a wonderful work. By the way, should I do denormalization after I get the results from smpl_registration/fit_SMPL_IPNet.py? I saw that in preprocess part, you do normalization first.
