### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by Tonight1121** [bharat-b7/IPNet#27]
Hello Bharat! Thank you so much for sharing this work!

I have just managed to install all the required environments. While I try the demo with provided command 

`python test_IPNet.py assets/scan.obj experiments/IPNet_p5000_01_exp_id01/checkpoints/checkpoint_epoch_249.tar out_dir -m IPNet`

The scripts is taking a lot of time "Loading weights from, experiments/IPNet_p5000_01_exp_id01/checkpoints/checkpoint_epoch_249.tar". And after a while, the system gives me the following error:

`RuntimeError: CUDA out of memory. Tried to allocate 4.01 GiB (GPU
15.78 GiB total capacity; 11.29 GiB already allocated; 235.19 MiBe; 11.33 GiB reserved in total by PyTorch)`

I was running this demo on a docker environment, using an empty "tesla v100-pcie-16gb" GPU. I was wondering whether this is enough space for a demo? If my problem is abnormal, do you have any idea why this is happening? I am very much appreciated for your help!

Best

**Comment by bharat-b7** [comment]
Hi, you can try reducing the number of points in `-batch_points` argument.

**Comment by Tonight1121** [comment]
> Hi, you can try reducing the number of points in `-batch_points` argument.

Hi thank you for the suggestions and I have generated "body.ply, cent.npy, full.ply, parts.npy" in the out_dir. Are they correct to expect?

Also, when I try to run the code "fit_SMPL_IPNet.py" to fit SMPLD to IPNet predictions, it throws me this error 

> FileNotFoundError: [Errno 2] No such file or directory: '/BS/RVH/work/data/template/faces.npy'

Do you have any idea what is this faces.npy? Are there more of these requires files for running the code? I would really much appreciate your help, and thanks in advance!

Best

**Comment by bharat-b7** [comment]
Hi,
faces.npy just contains smpl faces (smpl.f).
You can manually save this.
