### ISSUE TITLE
How to get a female SMPL fitting result?

### ISSUE THREAD

**Issue by daisyranc** [bharat-b7/IPNet#29]
I tried to use female data as input and changed the gender in fit SMPL part as 'female'. However，I still got the male-like SMPL result (SMPL-D was good). Could I get a female SMPL fitting result via fitting the SMPL part？

**Comment by crylingya** [comment]
Sorry! I found the answer. I missed other gender changes!

**Comment by daisyranc** [comment]
Sorry! I found the answer! I missed other gender changes! 
Thanks for your excellent work!!!
