### ISSUE TITLE
Boundary points of single view data?

### ISSUE THREAD

**Issue by heathentw** [bharat-b7/IPNet#34]
As I understood, the input "points" was sampled from the boundary of the mesh, which is reconstructed from complete scan of a real world object; my question is how to get the sampled points (for input) when we only have the points cloud from a single view (e.g. one depth camera)? as we don't have the complete mesh reconstructed, we can't sample the area which have no depth point clouds right?

Thank you for your time.

**Comment by bharat-b7** [comment]
Yes, you'll need full shape to supervise. This is to teach your network to complete the shape.

**Comment by heathentw** [comment]
@bharat-b7 May I ask for training IPNetMANO, do you use MANO parametric hand to produce fake data? will there be a domain gap between real/fake data? if so how will you guys handle it. thanks.
