### ISSUE TITLE
SMPL object has no property pose_subjects

### ISSUE THREAD

**Issue by ashwath98** [bharat-b7/IPNet#6]
Hey guys I'm trying to use your smpl_registration library to register SMPLD model to my scans,

I am using google colab with all the dependencies specified in your repo setup except for my python version being 3.6

when I run the following : python smpl_registration/fit_SMPLD.py <scan_obj> <result_dir>

this is the error I'm getting

**Traceback (most recent call last):
  File "smpl_registration/fit_SMPLD.py", line 174, in <module>
    gender=args.gender)
  File "smpl_registration/fit_SMPLD.py", line 96, in fit_SMPLD
    pose, betas, trans = fit_SMPL(scans, None, gender, save_path, display)
  File "/content/drive/My Drive/IPNet/smpl_registration/fit_SMPL.py", line 247, in fit_SMPL
    prior = get_prior(gender=gender)
  File "/content/drive/My Drive/IPNet/lib/th_smpl_prior.py", line 25, in get_prior
    prior = Prior(dp_prior.get_smpl())
  File "/content/drive/My Drive/IPNet/lib/th_smpl_prior.py", line 52, in __init__
    self.pose_subjects = sm.pose_subjects
AttributeError: 'add' object has no attribute 'pose_subjects'**

I also checked what were the members of the sm(smpl object) and it was the following
**['J', 'J_regressor', 'J_regressor_prior', 'J_transformed', 'T',**

I also did not see any vertex or face member included (I've not worked with smpl-pytorch yet so I'm unsure what are the expected member variables)

Do you guys have any idea what might be causing the issue?

I faced some issues with missing files(face.npy and model.pkl), which I resolved by creating  face.npy by converted the faces from (https://smpl.is.tue.mpg.de/) directly to numpy and for model.pkl I just used the male smpl model from (https://smpl.is.tue.mpg.de/)

**Comment by bharat-b7** [comment]
Hi, I've provided pre-stored prior in the assets folder. You can pass `precomputed=True` to `prior = get_prior(gender=gender, precomputed=True)`

**Comment by ashwath98** [comment]
Thank you for your response,
That addition resolved the issue with get_prior
If there is any way if I could help by sharing the changes I made to get it to work on colab please let me know

**Comment by bharat-b7** [comment]
It would be great if you can make a folder with your code and create a PR.
