### ISSUE TITLE
Python 3.6 or 3.7

### ISSUE THREAD

**Issue by gohyuchen** [bharat-b7/IPNet#7]
While trying to run demo IP Net
python test_IPNet.py assets/scan.obj experiments/IPNet_p5000_01_exp_id01/checkpoints/checkpoint_epoch_249.tar out_dir -m IPNet

This error was returned:
RuntimeWarning: compiletime version 3.6 of module 'utils.libs.libmesh.triangle_hash' does not match runtime version 3.7

The documentation states python 3.7 as a pre-requisite but the above error suggests we use 3.6. Can this be confirmed? Thanks.

**Comment by gohyuchen** [comment]
no longer encountering the error after removing hidden .git file from /mesh folder

**Comment by Bingoang** [comment]
@gohyuchen 
Hi~ I got the same error, but I can't find the "/mesh" folder. 
I only found "smplpytorch/.gitignore" and "utils/libs/libmesh/.gitignore".  I've removed the 2 files but still can't solve this error.
Hope you can give some adivce~

**Comment by gohyuchen** [comment]
can't remember where exactly was the folder. so far while working with SMPL, python 3.6 has worked well.

**Comment by Bingoang** [comment]
@gohyuchen Thanks very much~
