### ISSUE TITLE
Can I input point clouds without faces

### ISSUE THREAD

**Issue by legoc1986** [bharat-b7/IPNet#8]
Hi @bharat-b7 ,
   Thanks a lot for the release of code, and very interesting work!
   In the code fit_SMPL.py, the input scan.obj should contain faces. Could it possible that I only have point clouds (x,y,z) WITHOUT faces? 

BEST

**Comment by bharat-b7** [comment]
Hi, yes you can do this.
Currently we use bi-directional point-to-mesh distance ie. scan-to-smpl and smpl-to-scan.
You can edit [this line](https://github.com/bharat-b7/IPNet/blob/5df771b462d34684c07da6421a0b600a6bdbf083/smpl_registration/fit_SMPL.py#L71) to not compute smpl-to-scan distance as this is the only part that requires scan faces.

**Comment by legoc1986** [comment]
@bharat-b7  Thank you, and the demo with fit_SMPL.py works now
